const CardsData = [
  {
    projectName: "Card 1",
    imageUrl: "asset/img/hoodie.png",
    imageAlt: "Image 1",
    soft: "Figma , javascript, nodjs",
    memberSkills: [
      "Dev",
      "Graphiste",
      " ",
      "Filmaker",
      " ",
      "Photographe",
      " ",
      "Illustrateur",
    ],
    members: ["Gregory", " ", "Noname_spirit_boss_pimp"],
  },
  {
    projectName: "Card 2",
    imageUrl: "imag 2 ",
    imageAlt: "Image 2",
    soft: "Figma , javascript, nodjs",
    memberSkills: ["Illustrateur"],
    members: ["Gregory", " ", "Noname_spirit_boss_pimp"],
  },
  {
    projectName: "Card 3",
    imageUrl: "imag 3 ",
    imageAlt: "Image 3",
    soft: "Figma , javascript, nodjs",
    memberSkills: ["Dev", "Graphiste"],
    members: ["Gregory", " ", "Noname_spirit_boss_pimp"],
  },
  // Cartes supplémentaires avec des membres et des compétences aléatoires
  {
    projectName: "Card 4",
    imageUrl: "asset/img/card4.png",
    imageAlt: "Image 4",
    soft: "Figma , javascript, nodjs",
    memberSkills: ["Dev", "Filmaker", " ", "Graphiste"],
    members: ["Alice", " ", "John_Doe"],
  },
  {
    projectName: "Card 5",
    imageUrl: "asset/img/card5.png",
    imageAlt: "Image 5",
    soft: "Figma , javascript, nodjs",
    memberSkills: ["Photographe", " ", "Illustrateur"],
    members: ["Gregory", " ", "Jane_Smith"],
  },
  {
    projectName: "Card 6",
    imageUrl: "asset/img/card6.png",
    imageAlt: "Image 6",
    soft: "Figma , javascript, nodjs",
    memberSkills: ["Graphiste", "Filmaker", " ", "Photographe"],
    members: ["Tom", " ", "Alex_Boss"],
  },
  {
    projectName: "Card 7",
    imageUrl: "asset/img/card7.png",
    imageAlt: "Image 7",
    soft: "Figma , javascript, nodjs",
    memberSkills: ["Dev", " ", "Photographe"],
    members: ["Sarah", " ", "Max_Tech"],
  },
  {
    projectName: "Card 8",
    imageUrl: "asset/img/card8.png",
    imageAlt: "Image 8",
    soft: "Figma , javascript, nodjs",
    memberSkills: ["Filmaker", "Graphiste"],
    members: ["David", " ", "Luna"],
  },
  {
    projectName: "Card 9",
    imageUrl: "asset/img/card9.png",
    imageAlt: "Image 9",
    soft: "Figma , javascript, nodjs",
    memberSkills: ["Dev", "Filmaker"],
    members: ["Eve", " ", "Chris_Tech"],
  },
  {
    projectName: "Card 10",
    imageUrl: "asset/img/card10.png",
    imageAlt: "Image 10",
    soft: "Figma , javascript, nodjs",
    memberSkills: ["Graphiste", "Illustrateur", " ", "Dev"],
    members: ["Mia", " ", "Rico"],
  },
];

export default CardsData;
